runtime: nodejs12
service: backend

env_variables:
  TOURNAMENT_MONGO_USERNAME: ${TOURNAMENT_MONGO_USERNAME}
  TOURNAMENT_MONGO_PASSWORD: ${TOURNAMENT_MONGO_PASSWORD}
  TOURNAMENT_MONGO_DATABASE: Tournament-Masterpiece
  TOURNAMENT_MONGO_PROTOCOL: mongodb+srv
  TOURNAMENT_MONGO_HOST: cluster0-7rybn.mongodb.net
