runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /(.*\.(js|css|png|gif|svg|map|ttf|woff|woff2))$
  static_files: dist/Tournament-masterpiece/\1
  upload: dist/Tournament-masterpiece/.*\.(js|css|png|gif|svg|map|ttf|woff|woff2)$

- url: /
  static_files: dist/Tournament-masterpiece/index.html
  upload: dist/Tournament-masterpiece/index.html

- url: /.*
  static_files: dist/Tournament-masterpiece/index.html
  upload: dist/Tournament-masterpiece/index.html

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
