@startuml

' MCD

Interface Learns{

}

Interface Leads{

}
Interface Masters{

}

class DEVELOPER{
 ipn
 firstname
 lastname
 birthdate
 join_date
}

class technology{
  code
  fr
  en
}




DEVELOPER 	}o-- Learns : 0,n
Learns --o{ technology : 0,n
DEVELOPER }o-- Leads : 0,n
Leads |o-- DEVELOPER : 0,1
Masters --|| DEVELOPER : 0,1
Masters ||--o{ technology : 1,n

@enduml
