@startuml

' MPD

class developer{
  id_dev Integer <PK>
  --
  firstname varcar(20)
  lastname varcar(20)
  ipn varcar(8)
  birthdate Date
  --
  mainTechCode <FK>
}


class technology{
  id_tech <PK>
  code varChar(7)
  fr varChar(30)
  en varChar(30)
}

class learning_technology{
  id_learning <PK>
  tech_code varChar(7)
  ipn varChar(8)
}

 
developer <---- learning_technology
technology <--- learning_technology

@enduml
